name:                unicode-character-ranges
version:             0.1.0.0
github:              "sjakobi/unicode-character-ranges"
license:             BSD3
author:              "Simon Jakobi"
maintainer:          "simon.jakobi@gmail.com"
copyright:           "Copyright (c) 2019 Simon Jakobi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sjakobi/unicode-character-ranges#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- range-set-list

library:
  source-dirs: src

executables:
  unicode-character-ranges-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unicode-character-ranges

tests:
  unicode-character-ranges-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unicode-character-ranges
